local opt = vim.opt
opt.shiftwidth = 2
opt.expandtab = true
opt.tabstop = 2
opt.number = true
opt.relativenumber = true
opt.smartcase = true
opt.splitright = true
opt.signcolumn = "yes:2"
opt.mouse = "a"
opt.termguicolors = true
opt.showmode = false
opt.colorcolumn = "80,120"
opt.clipboard = "unnamedplus"
opt.cursorline = true
opt.ignorecase = true
opt.wrap = false
opt.confirm = true
opt.laststatus = 3
-- vim.opt.statuscolumn = [[%!v:lua.require'snacks.statuscolumn'.get()]]
-- vim.opt.autoformat = false

PICKER = "snacks.pick" -- options: telescope.nvim, fzf-lua, mini.pick, snacks.pick
vim.g.edge_enable_italic = true
vim.g.edge_style = "neon"
vim.g.sonokai_style = "atlantis"
vim.g.sonokai_enable_italic = true
