local opt = vim.opt
opt.shiftwidth = 2
opt.expandtab = true
opt.tabstop = 2
opt.number = true
opt.relativenumber = true
opt.smartcase = true
opt.splitright = true
opt.signcolumn = "yes:2"
opt.mouse = "a"
opt.termguicolors = true
opt.showmode = false
opt.colorcolumn = "80,120"
opt.clipboard = "unnamedplus"
opt.cursorline = true
opt.ignorecase = true
opt.wrap = false
opt.confirm = true
-- vim.opt.statuscolumn = [[%!v:lua.require'snacks.statuscolumn'.get()]]
-- vim.opt.autoformat = false

PICKER = "fzf-lua"
